​export const state = () => ({
	all: [
​ 		{
			id: 0,
			url_name: 'friisila',
			name: 'Gasum Espoo Friisilä',
			address: 'Kuitinmäentie 26, 02240 Espoo',
			coords: { lat: 60.1617785, lng: 24.7172848},
			products: ['Maakaasu (CNG)','Biokaasu (CBG)'],
			payment: ['Gasum GasCard -tankkauskortti','Pankki- & luottokortit'],
			operator: 'Gasum',
			type: 'marker',
		},
​ 		{
			id: 1,
			url_name: 'lommila',
			name: 'Gasum Espoo Lommila IKEA',
			address: 'Espoontie 21, 02740 Espoo',
			coords: { lat: 60.2165252, lng: 24.6664632},
			products: ['Maakaasu (CNG)','Biokaasu (CBG)'],
			payment: ['Gasum GasCard -tankkauskortti','Pankki- & luottokortit'],
			operator: 'Gasum',
			type: 'marker',
		},
		{
			id: 2,
			url_name: 'vermo',
			name: 'Gasum Espoo Vermo',
			address: 'Perkkaantie 17, 00370 Espoo',
			coords: { lat: 60.2173457, lng: 24.8351607},
			products: ['Maakaasu (CNG)','Biokaasu (CBG)'],
			payment: ['Gasum GasCard -tankkauskortti','Pankki- & luottokortit'],
			operator: 'Gasum',
			type: 'marker',
		},
		{
			id: 3,
			url_name: 'kiimassuo',
			name: 'Forssa Kiimassuo',
			address: 'Voimalankatu 56, 30420 Forssa',
			coords: { lat: 60.7916559, lng: 23.5885101},
			products: ['Biokaasu (CBG)'],
			payment: ['EG Biogas -tankkauskortti'],
			operator: 'Envor Group',
			type: 'marker',
		},
		{
			id: 4,
			url_name: 'poitsila',
			name: 'Hamina Poitsila',
			address: 'Helsingintie 1 B, 49410 Hamina',
			coords: { lat: 60.5635916, lng: 27.1617594},
			products: ['Biokaasu (CBG)'],
			payment: ['Pankki- & luottokortit'],
			operator: 'ST1,Haminan Energia',
			type: 'marker',
		},
		{
			id: 5,
			url_name: 'hermanni',
			name: 'Gasum Helsinki Hermanni',
			address: 'Vanha Talvitie 21, 00580 Helsinki',
			coords: { lat: 60.1922798, lng: 24.9779427},
			products: ['Maakaasu (CNG)','Biokaasu (CBG)'],
			payment: ['Gasum GasCard -tankkauskortti','Pankki- & luottokortit'],
			operator: 'Gasum',
			type: 'marker',
		},
		{
			id: 6,
			url_name: 'malmi',
			name: 'Gasum Helsinki Malmi',
			address: 'Tattariharjuntie 41, 00700 Helsinki',
			coords: { lat: 60.2529849, lng: 25.0633955},
			products: ['Maakaasu (CNG)','Biokaasu (CBG)'],
			payment: ['Gasum GasCard -tankkauskortti','Pankki- & luottokortit'],
			operator: 'Gasum',
			type: 'marker',
		},
		{
			id: 7,
			url_name: 'roihupelto',
			name: 'Gasum Helsinki Roihupelto',
			address: 'Viilarintie 7, 00880 Helsinki',
			coords: { lat: 60.2138918, lng: 25.0598805},
			products: ['Maakaasu (CNG)','Biokaasu (CBG)'],
			payment: ['Gasum GasCard -tankkauskortti','Pankki- & luottokortit'],
			operator: 'Gasum',
			type: 'marker',
		},
		{
			id: 8,
			url_name: 'ruskeasuo',
			name: 'Gasum Helsinki Ruskeasuo',
			address: 'Hakamäenkuja 1, 00310 Helsinki',
			coords: { lat: 60.207332, lng: 24.905677},
			products: ['Maakaasu (CNG)','Biokaasu (CBG)'],
			payment: ['Gasum GasCard -tankkauskortti','Pankki- & luottokortit'],
			operator: 'Gasum',
			type: 'marker',
		},
		{
			id: 9,
			url_name: 'vuosaari',
			name: 'Gasum Helsinki Vuosaari',
			address: 'Provianttikatu 6, 00960 Helsinki',
			coords: { lat: 60.2223017, lng: 25.1762191},
			products: [Nesteytetty maakaasu (LNG)],
			payment: ['Gasum GasCard -tankkauskortti','Pankki- & luottokortit'],
			operator: 'Gasum',
			type: 'marker',
		},
		{
			id: 10,
			url_name: 'palopuro',
			name: 'Hyvinkää Palopuro',
			address: 'Haapasaarentie 75, 05470 Hyvinkää',
			coords: { lat: 60.5964257, lng: 24.9265945},
			products: ['Biokaasu (CBG)'],
			payment: ['Pankki- & luottokortit'],
			operator: 'Palopuron Biokaasu,Nivos',
			type: 'marker',
		},
		{
			id: 11,
			url_name: 'sahanmaki',
			name: 'Gasum Hyvinkää Sahanmäki',
			address: 'Kerkkolankatu 39, 05800 Hyvinkää',
			coords: { lat: 60.6567101, lng: 24.8480165},
			products: ['Maakaasu (CNG)','Biokaasu (CBG)'],
			payment: ['Gasum GasCard -tankkauskortti','Pankki- & luottokortit'],
			operator: 'Gasum',
			type: 'marker',
		},
		{
			id: 12,
			url_name: 'tiirio',
			name: 'Gasum Hämeenlinna Tiiriö',
			address: 'Paroistentie 2, 13600 Hämeenlinna',
			coords: { lat: 61.0157378, lng: 24.4157302},
			products: ['Maakaasu (CNG)','Biokaasu (CBG)'],
			payment: ['Gasum GasCard -tankkauskortti','Pankki- & luottokortit'],
			operator: 'Gasum',
			type: 'marker',
		},
		{
			id: 13,
			url_name: 'korvenranta',
			name: 'Gasum Imatra Korvenranta',
			address: 'Kertakaari 4, 55120 Imatra',
			coords: { lat: 61.1862904, lng: 28.7454718},
			products: ['Maakaasu (CNG)','Biokaasu (CBG)'],
			payment: ['Gasum GasCard -tankkauskortti','Pankki- & luottokortit'],
			operator: 'Gasum',
			type: 'marker',
		},
		{
			id: 14,
			url_name: 'isokyro',
			name: 'Isokyrö',
			address: 'Kalpatie 2, 61500 Isokyrö',
			coords: { lat: 61.1862904, lng: 28.7454718},
			products: ['Biokaasu (CBG)'],
			payment: ['Pankki- & luottokortit'],
			operator: 'Jeppo Biogas,Kyrö Distillery Company',
			type: 'marker',
		},
		{
			id: 15,
			url_name: 'joutsa',
			name: 'Joutsa',
			address: 'Mämmiläntie 38, 19650 Joutsa',
			coords: { lat: 61.7499478, lng: 26.1014101},
			products: ['Biokaasu (CBG)'],
			payment: ['Pankki- & luottokortit'],
			operator: 'Joutsan Ekokaasu,Metener',
			type: 'marker',
		},
		{
			id: 16,
			url_name: 'kanavuori',
			name: 'Gasum Jyväskylä Kanavuori',
			address: 'Metsälehmuksentie 9, 40800 Jyväskylä',
			coords: { lat: 62.2313269, lng: 25.9162483},
			products: ['Nesteytetty maakaasu (LNG)'],
			payment: ['Gasum GasCard -tankkauskortti','Pankki- & luottokortit'],
			operator: 'Gasum',
			type: 'marker',
		},
		{
			id: 17,
			url_name: 'mustankorkea',
			name: 'Jyväskylä Mustankorkea',
			address: 'Ronsuntaipaleentie 204, 40500 Jyväskylä',
			coords: { lat: 62.2137324, lng: 25.6691426},
			products: ['Biokaasu (CBG)'],
			payment: ['Pankki- & luottokortit'],
			operator: 'Mustankorkea',
			type: 'marker',
		},
		{
			id: 18,
			url_name: 'petikko',
			name: 'Gasum Vantaa Petikko',
			address: 'Klinkkerikaari 1, 01720 Vantaa',
			coords: { lat: 60.279438, lng: 24.815312},
			products: ['Maakaasu (CNG)','Biokaasu (CBG)'],
			payment: ['Gasum GasCard -tankkauskortti','Pankki- & luottokortit'],
			operator: 'Gasum',
			type: 'marker',
		},
		{
			id: 19,
			url_name: 'tuupakka',
			name: 'Gasum Vantaa Tuupakka',
			address: 'Tuupakantie 25, 01690 Vantaa',
			coords: { lat: 60.293188, lng: 24.913438},
			products: ['Maakaasu (CNG)','Biokaasu (CBG)','Nesteytetty maakaasu (LNG)','Nesteytetty biokaasu (LBG)'],
			payment: ['Gasum GasCard -tankkauskortti','Pankki- & luottokortit'],
			operator: 'Gasum',
			type: 'marker',
		},
	],
});
